from .adaptadores import NotificadorEmail, ProveedorFechaSistema
from .repositorios_memoria import RepositorioEquiposMemoria, RepositorioEstudiantesMemoria, RepositorioPrestamosMemoria
from .repositorios_sql import RepositorioEquiposSQL, RepositorioEstudiantesSQL, RepositorioPrestamosSQL
